# Generated by Django 4.0.4 on 2022-05-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created',
        ),
        migrations.RemoveField(
            model_name='city',
            name='house_pic',
        ),
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('house_pic', models.ImageField(null=True, upload_to='')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='home_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.home'),
        ),
    ]
