# Generated by Django 4.0.4 on 2022-05-16 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_city_created_remove_city_house_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
